### ISSUE TITLE
Vcpkg installation problem

### ISSUE THREAD

**Issue by Belkovinov** [minio/minio-cpp#104]
I did `vcpkg install minio-cpp` and Qt Creator could not find package configuration file.
"error: Could not find a package configuration file provided by "miniocpp" with any of the following names: miniocppConfig.cmake miniocpp-config.cmake Add the installation prefix of "miniocpp" to CMAKE_PREFIX_PATH or set "miniocpp_DIR" to a directory containing one of the above files.  If "miniocpp" provides a separate development package or SDK, be sure it has been installed."
Vcpkg can install another libraries ant they work in Qt Creator.
My OS is Ubuntu 23.10
What can corrupt installation?

**Comment by balamurugana** [comment]
Below cmake works fine
```
cmake_minimum_required(VERSION 3.10)
project(hello)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED True)
set(EXECUTABLE_OUTPUT_PATH ${CMAKE_BINARY_DIR}/bin)

if("${CMAKE_BINARY_DIR}" STREQUAL "${CMAKE_SOURCE_DIR}")
  message(FATAL_ERROR "FATAL: In-source builds are not allowed. You should create a separate directory for build files.")
endif()

set(requiredlibs)

if(CMAKE_COMPILER_IS_GNUCC)
  set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -Werror")
  if(CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL 8.0 AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 9.0 AND NOT MINGW)
    list(APPEND requiredlibs stdc++fs)
  endif()
endif()

find_path(MINIOCPP_INCLUDE_DIRS miniocpp/client.h)
find_library(MINIOCPP_LIBRARIES miniocpp)
include_directories(${MINIOCPP_INCLUDE_DIRS})
list(APPEND requiredlibs ${MINIOCPP_LIBRARIES})

message(STATUS "Found required libs: ${requiredlibs}")

add_executable(hello main.cpp)
target_link_libraries(hello ${requiredlibs})
```

**Comment by Belkovinov** [comment]
> Below cmake works fine
> 
> ```
> cmake_minimum_required(VERSION 3.10)
> project(hello)
> 
> set(CMAKE_CXX_STANDARD 17)
> set(CMAKE_CXX_STANDARD_REQUIRED True)
> set(EXECUTABLE_OUTPUT_PATH ${CMAKE_BINARY_DIR}/bin)
> 
> if("${CMAKE_BINARY_DIR}" STREQUAL "${CMAKE_SOURCE_DIR}")
>   message(FATAL_ERROR "FATAL: In-source builds are not allowed. You should create a separate directory for build files.")
> endif()
> 
> set(requiredlibs)
> 
> if(CMAKE_COMPILER_IS_GNUCC)
>   set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -Werror")
>   if(CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL 8.0 AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 9.0 AND NOT MINGW)
>     list(APPEND requiredlibs stdc++fs)
>   endif()
> endif()
> 
> find_path(MINIOCPP_INCLUDE_DIRS miniocpp/client.h)
> find_library(MINIOCPP_LIBRARIES miniocpp)
> include_directories(${MINIOCPP_INCLUDE_DIRS})
> list(APPEND requiredlibs ${MINIOCPP_LIBRARIES})
> 
> message(STATUS "Found required libs: ${requiredlibs}")
> 
> add_executable(hello main.cpp)
> target_link_libraries(hello ${requiredlibs})
> ```

Thank you. It was error in cmakelists file. Now library is connected to the project. 

Now i get this problem when i added minio-cpp in the project. What could cause it to happen?
![image](https://github.com/minio/minio-cpp/assets/105446141/6943a78c-0acb-4f24-83d6-0e4416d42708)
