### ISSUE TITLE
Clang-format-18 formats the source code differently

### ISSUE THREAD

**Issue by HJLebbink** [minio/minio-cpp#117]
My `clang-format` gives `clang-format version 18.0.0git (https://github.com/llvm/llvm-project.git 02e02b9a8f0e22ffc0d6c070b132a88e94f02861)` and it give different formatted source code. 

Q1: can we log/print the used clang version just for reproducibility. Ubuntu clang-format version 14.0.0-1ubuntu1.1 works.
Q2: can we check-in the used style-sheet such that we are less dependent on the LLVM version that people happen to have installed.

**Comment by balamurugana** [comment]
I use 
```
$ clang-format --version
clang-format version 17.0.6 (Fedora 17.0.6-2.fc39)
```
which works fine with Github CI.

May be the latest version `18.1.1` fixes the issue?!

**Comment by kobalicek** [comment]
At the moment CI runs these formatters:

  - Ubuntu clang-format version 14.0.6
  - clang-format version 17.0.6

Clang-format 18 formats the source code differently. Once I make the CI happy I would add reviewers to this PR:

  - https://github.com/minio/minio-cpp/pull/123

**Comment by kobalicek** [comment]
This should be resolved, we have moved to clang-18 for source code formatting.
