### ISSUE TITLE
localtime function and DST

### ISSUE THREAD

**Issue by andy3469** [minio/minio-cpp#132]
There is a problem of RequestTimeTooSkewed when you try to connect to a server while the timezone is in DST mode.

When you add [x-amx-date](https://github.com/minio/minio-cpp/blob/main/src/request.cc#L334) to the request header, the function [localtime is called](https://github.com/minio/minio-cpp/blob/main/src/utils.cc#L329).

I know that all the communication are done in UTC as noted in the PR #115. 
The thing is, when the PC is set in DST (daylight), localtime add 1 hour to the returned time.
If I disable DST, it's working correctly.

PS: I'm working on Windows

**Comment by balamurugana** [comment]
@andy3469 looks like MS Windows issue. Can you do `Client.Debug(true)` and share the output?

**Comment by ijoseph** [comment]
Wow, topical. I just fought through this on macOS last night.  This fixed it:

```diff
diff --git a/src/utils.cc b/src/utils.cc
index 5204547..f3418be 100644
--- a/src/utils.cc
+++ b/src/utils.cc
@@ -337,7 +337,9 @@ UtcTime UtcTime::Now() {
   auto usec_now = std::chrono::system_clock::now().time_since_epoch() /
                   std::chrono::microseconds(1);
   auto secs_local = static_cast<time_t>(usec_now / 1000000);
-  auto secs_utc = std::mktime(std::gmtime(&secs_local));
+  auto tm_time = std::gmtime(&secs_local);
+  tm_time->tm_isdst = - 1;
+  auto secs_utc = std::mktime(tm_time);
   return UtcTime(secs_utc, static_cast<long>(usec_now % 1000000));
 }
``` 

The issue, [as they mention here](https://stackoverflow.com/a/38690449/588437), is that the `std::tm*` returned by `std::gmtime` has the `tm_isdst` flag set to `0`, which then causes `std::mktime` to wrongfully adjust the time when converting this back into a `std::time_t`.

**Comment by balamurugana** [comment]
@andy3469  Can you confirm whether the PR https://github.com/minio/minio-cpp/pull/133 fixes the issue?

**Comment by andy3469** [comment]
Yes the PR #133 fixes the issue correctly
