### ISSUE TITLE
[question]How to trust the minio server that uses the self-signed certificate?

### ISSUE THREAD

**Issue by bboy-hui** [minio/minio-cpp#138]
1.When I use mc client to connect to a server that uses a self-signed certificate, it prompts mc: Unable to initialize new alias from the provided credentials. Get "https://192.168.xx.xx:9000": tls: failed to verify certificate: x509: certificate signed by unknown authority.
2.Trust the self-signed certificate using environmental variables export SSL_CERT_FILE=/home/test/hbd/minioserver.crt
3.I can connect to the server using the MC  client but using the C++ SDK client can not connect the server.
How to trust the minio server that uses the self-signed certificate?

**Comment by balamurugana** [comment]
Use [SetSslCertFile()](https://github.com/minio/minio-cpp/blob/main/include/miniocpp/baseclient.h#L63)
