### ISSUE TITLE
BucketExists() blocks when the server is unreachable

### ISSUE THREAD

**Issue by lxily** [minio/minio-cpp#146]
I'm encountering an issue with the `BucketExists()` function. When I use this function to check for the existence of a bucket, and the MinIO server is down or unreachable, the function seems to block indefinitely at `select(maxfd + 1, &fdread, &fdwrite, &fdexcep, nullptr)`.

Is there a way to avoid this blocking behavior, perhaps by implementing a timeout mechanism? Any guidance on how to handle this situation would be greatly appreciated.

Thank you!

**Comment by balamurugana** [comment]
Refer https://github.com/minio/minio-cpp/issues/125
