### ISSUE TITLE
PutObject file size issue

### ISSUE THREAD

**Issue by skydream-xu** [minio/minio-cpp#152]
``	minio::s3::BaseUrl base_url("xxxxxx:9000", false);

	// Create credential provider.
	minio::creds::StaticProvider provider(
		"xxxx", "xxxxx");

	// Create S3 client.
	minio::s3::Client client(base_url, &provider);

	// Create put object arguments.
	std::ifstream file("d:/test.step",std::ios::in);
	file.seekg(0, std::ios::end);

	std::streamsize size = file.tellg();
	file.seekg(0, std::ios::beg);
	minio::s3::PutObjectArgs args(file, size, 0);
	args.bucket = "xhb";
	args.object = "test.step";

	// Call put object.
	minio::s3::PutObjectResponse resp = client.PutObject(args);

run env:
        windows

Error info :
     not enough data in the stream; expected: 146060, got: 142859 bytes

**Comment by balamurugana** [comment]
1. Check your file size in the OS
2. Use proper open flags
