### ISSUE TITLE
Http status code 0 on ARM64 Ubuntu 20.04

### ISSUE THREAD

**Issue by fernwer** [minio/minio-cpp#153]
I try to run the BucketExists.cc to check the connectivity to the my MinIO cluster. Here is my code: 

![image](https://github.com/minio/minio-cpp/assets/12730207/ecd7a9a2-6969-451c-ac72-b6a5f185a88b)

However, while I try to run the code, the result is unchanged as followed:
![image](https://github.com/minio/minio-cpp/assets/12730207/feb1f8a6-4f58-43c8-a1a6-1cc3c51ea600)

At first I thought it may be an url misconfiguration,  so I tried changing the url in different formats but it never worked, after that I also tried pinging the server and the server network was connected.

But when I change the code to Python version, everything seems fine. 
![image](https://github.com/minio/minio-cpp/assets/12730207/5efd72e0-21ce-446e-af0d-246b61a3daf3)

So is there anything wrong with my connection configuration in C++ version ?

**Comment by balamurugana** [comment]
Your MinIO server is running with TLS, but you are accessing non-TLS.

**Comment by anhnhust** [comment]
Sorry @fernwer , I encountered the same error. How did you solve it before?
