### ISSUE TITLE
Release timeline

### ISSUE THREAD

**Issue by aliddell** [minio/minio-cpp#154]
The issue in #150 appears to be fixed in `main`, but affects users of the 0.2.0 release. Is there an estimated timeline for the next release? I'm particularly interested in when the fix release makes it into vcpkg, as that seems to be the current [recommended installation method](https://github.com/minio/minio-cpp?tab=readme-ov-file#installation-via-vcpkg).

N.B., I tried to ask about this on the Slack but never got a response.

**Comment by balamurugana** [comment]
@harshavardhana We would need to make a new minor release based on release time cycle.

**Comment by balamurugana** [comment]
@aliddell Stay tuned!
