### ISSUE TITLE
RequestTimeTooSkewed authentication failure.

### ISSUE THREAD

**Issue by DKGH** [minio/minio-cpp#155]
While trying to connect to a database in my organization, I am getting a similar error as described here: https://github.com/minio/minio-java/issues/701. I can connect to this database server using Chrome from the same client. I can also connect using minio-cpp if I tweak my time-zone a little bit. Please see if it is possible to disable time check or use another method of authentication which doesn't involve time check?

**Comment by harshavardhana** [comment]
> While trying to connect to a database in my organization, I am getting a similar error as described here: [minio/minio-java#701](https://github.com/minio/minio-java/issues/701). I can connect to this database server using Chrome from the same client. I can also connect using minio-cpp if I tweak my time-zone a little bit. Please see if it is possible to disable time check or use another method of authentication which doesn't involve time check?

Unfortunately, time checks are the basis of AWS S3 signature; they cannot be turned off. Fix your system to have synchronized times via NTP.

**Comment by aliddell** [comment]
@harshavardhana I doubt "Fix your system to have synchronized times via NTP" is the right answer when when `RequestTimeTooSkewed` is [known to be the symptom of a broken 0.2.0 release](https://github.com/minio/minio-cpp/issues/150).

**Comment by kobalicek** [comment]
@harshavardhana Is there anything preventing us from updating minio-cpp on vcpkg? I also think there should be a new release if users are having problems with the current release.

**Comment by DKGH** [comment]
@harshavardhana I was able to connect with Chrome and also Aws SDK Cpp. I would still prefer this because this seems lightweight. Please see if new version can be released soon to vcpkg.

**Comment by mateuszwojt** [comment]
@harshavardhana is it possible to get an ETA on minio-cpp package update in vcpkg?
