### ISSUE TITLE
Server failed with HTTP status code 0

### ISSUE THREAD

**Issue by anhnhust** [minio/minio-cpp#157]
Althougth I change http to https but i still meet this error
![er](https://github.com/user-attachments/assets/6bf2002d-7b44-421f-9d3c-3402afef837d)

**Comment by balamurugana** [comment]
@anhnhust Firstly you would need to check how your server is running and the server should be accessible. Also check your firewall/proxy/load-balancer etc.

**Comment by balamurugana** [comment]
Refer https://github.com/minio/minio-cpp/issues/153#issuecomment-2225269777
