### ISSUE TITLE
minio-cpp is only supported on '!windows & !uwp'

### ISSUE THREAD

**Issue by mikrosk** [minio/minio-cpp#159]
When trying to build `minio-cpp` from Visual Studio I got:
```
minio-cpp is only supported on '!windows & !uwp', which does not match x64-windows. This usually means that there are known build failures, or runtime problems, when building other platforms. To ignore this and attempt to build minio-cpp anyway, rerun vcpkg with `--allow-unsupported`.
```
Is this expected? If so, shouldn't this be mentioned in README.md?

**Comment by mikrosk** [comment]
Hmm, I guess it's because this error:
```
<user>\source\repos\ConsoleApplication3\vcpkg_installed\x64-windows\vcpkg\blds\minio-cpp\src\v0.1.1-c280f46adc.clean\include\http.h(19): fatal error C1083: Cannot open include file: 'arpa/inet.h': No such file or directory
```
So minio-cpp is really not supported on Windows?

**Comment by balamurugana** [comment]
@mikrosk We have MS Windows CI build for every PR. Looks like you have local issue.

**Comment by mikrosk** [comment]
@balamurugana local in what sense? `vcpkg` is installed automatically in Visual Studio, the warning is printed because minio-cpp itself has explicitly forbidden building on windows. Are you sure your triplet isn't something like msys, cygwin or similar?

**Comment by mikrosk** [comment]
I see that the CI is using CMake to build minio-cpp, not MS Build, maybe that's the issue. Otherwise my build log looks pretty much the same as on CI.

**Comment by balamurugana** [comment]
@mikrosk Refer https://github.com/minio/minio-cpp#build-requirements

I guess we don't support other than mentioned in the build requirements.

**Comment by mikrosk** [comment]
Indeed, replicating the commands from the CI resulted in a finished build. I need to check out what's going on with the integrated `vcpkg` in Visual Studio then, it should do the same and yet it doesn't.

However there was one thing which I didn't understand: how come that your CI executes `bootstrap-vcpkg.sh` and not `bootstrap-vcpkg.bat` (which I had to do) ? According to the CI info, it is supposed to run on powershell in Windows server, so it shouldn't be able to execute linux scripts?

**Comment by balamurugana** [comment]
Check https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#language-and-runtime and https://github.com/minio/minio-cpp/blob/main/.github/workflows/ci.yml#L85

I am closing this issue as it is not a problem of `minio-cpp`.

**Comment by kobalicek** [comment]
@mikrosk I think you have old vcpkg (the port tree), because minio-cpp probably has `!windows` in vcpkg.json in the past, but now it's not present there (Windows platform is supported).

**Comment by mikrosk** [comment]
Petr, that's a great hint, thanks. I'm still very new to vcpkg so I hadn't realised that there could be different database versions.
