### ISSUE TITLE
Unexpanded user agent string

### ISSUE THREAD

**Issue by piotr-topnotch** [minio/minio-cpp#161]
In the `BaseClient::user_agent_` member, I can see `MinIO (windows; x86_64) minio-cpp/MINIO_CPP_MAJOR_VERSION.MINIO_CPP_MINOR_VERSION.MINIO_CPP_PATCH_VERSION` content, which looks wrong. I'd expect the `MINIO_CPP_MAJOR_VERSION`, etc., to be replaced with their numeric values.

**Comment by balamurugana** [comment]
Regression since #121
