### ISSUE TITLE
Bad copy-paste in types.cc

### ISSUE THREAD

**Issue by sminux** [minio/minio-cpp#164]
Hi, devs!
I think in function 'ToXML': Value 'noncurrent_version_expiration_noncurrent_days' might be 'noncurrent_version_transition_noncurrent_days'

https://github.com/minio/minio-cpp/blob/cd4ef14955201d5ce81e54155ef0980f7c644864/src/types.cc#L570

**Comment by balamurugana** [comment]
Feel free to send a PR
