### ISSUE TITLE
is vcpkg arm64-osx version outdated?

### ISSUE THREAD

**Issue by Clement-Jean** [minio/minio-cpp#40]
I tried to install miniocpp with vcpkg on my mac M1 and when I look at the include folder in miniocpp (~/vcpkg/installed/arm64-osx/include/miniocpp) I can only see the following:

├── s3.h
├── s3_headers.h
├── s3_http.h
├── s3_io.h
├── s3_signature_v2.h
└── s3_types.h

This doesn't match with what's on the repository. Is it because the version is outdated?

**Comment by harshavardhana** [comment]
vcpkg is not updated yet, since we have been rewriting the library for completeness and C++ idiomatic implementation.

**Comment by Clement-Jean** [comment]
Alright, is there any way that I can use this library right now? Or is there any way I can help you guys?

**Comment by harshavardhana** [comment]
> Alright, is there any way that I can use this library right now? Or is there any way I can help you guys?

just `git clone` and following the build instructions

**Comment by gocpplua** [comment]
> vcpkg is not updated yet, since we have been rewriting the library for completeness and C++ idiomatic implementation.

I've been using vcpkg but with no success, turns out this is the reason
