### ISSUE TITLE
PutObject error

### ISSUE THREAD

**Issue by gocpplua** [minio/minio-cpp#41]
https://github.com/minio/minio-cpp/blob/main/examples/PutObject.cc

I refer to the above file and I get an error when I execute PutObject"：
server failed with HTTP status code 0

**Comment by balamurugana** [comment]
curlpp is unable to connect to the server and not returning any error, like you are connecting to `http` server with `https` or other way around. Just enable [Debug](https://github.com/minio/minio-cpp/blob/main/include/baseclient.h#L48) and share the log.

**Comment by 541230762** [comment]
你好，请问是如何解决的
