### ISSUE TITLE
No we can use vcpkg install this lib

### ISSUE THREAD

**Issue by drip-hailin** [minio/minio-cpp#46]
![image](https://user-images.githubusercontent.com/51024883/187501632-49eb16db-d5e1-4827-b882-94425e8aed91.png)

？

**Comment by harshavardhana** [comment]
Windows is not supported yet @drip-hailin use Linux or macOS at the moment.

**Comment by drip-hailin** [comment]
@harshavardhana 
Building source   
Windows is not supported yet ?

**Comment by harshavardhana** [comment]
> @harshavardhana Building source Windows is not supported yet ?

No, it is not @drip-hailin we may never support windows at this point. Feel free to port this library to Windows yourself we are happy to accept such PRS.

**Comment by drip-hailin** [comment]
Thanks




---Original---
From: ***@***.***&gt;
Date: Mon, Sep 5, 2022 13:31 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [minio/minio-cpp] No we can use vcpkg install this lib (onwindows) (Issue #46)




  
@harshavardhana Building source Windows is not supported yet ?
  
No, it is not @drip-hailin we may never support windows at this point. Feel free to port this library to Windows yourself we are happy to accept such PRS.
