### ISSUE TITLE
GetObjectResponse doesn't keep data (resp.data)

### ISSUE THREAD

**Issue by sungin-h** [minio/minio-cpp#57]
Hi, 
I'm new to both MINIO and minio-cpp.

From [GetObject.cc example](https://github.com/minio/minio-cpp/blob/main/examples/GetObject.cc), 
I printed the data of GetObjectResponse as below, but it printed nothing.

minio::s3::GetObjectResponse resp = client.GetObject(args);
if (resp) {
   std::cout << resp.data ;
}

Within datafunc, args.datachunk is available. 
However, I'd like to compute the data using GPU(i.e., CUDA), so computing within datafunc can't be an option for me.

To fix this issue, I added 
body += std::string(buffer ,length); to [http.cc at line 160](https://github.com/minio/minio-cpp/blob/main/src/http.cc#L160) 

Which way is a proper scheme of MINIO?

1) Response keeps data when GetObject() is invoked w\ datafunc (my method)
2) Allowing GetObject() can be invoked w\o datafunc (currently this case is not allowed by [here](https://github.com/minio/minio-cpp/blob/main/src/args.cc#L181))
3) Response keeps data when both GetObject() is invoked w/ and w\o datafunc

thank you.

FYI, my environment as below:
OS: Ubuntu 18.04
g++: v8.4.0
nvcc: V11.8.89 (CUDA 11.8)

**Comment by balamurugana** [comment]
Refer https://github.com/minio/minio-cpp/blob/main/examples/GetObject.cc how to use `GetObject()`.  As `libcurl` is lazy on incoming data, hence `minio-cpp`. There is no other way to do so.
