### ISSUE TITLE
can we support compile in alpine?

### ISSUE THREAD

**Issue by HandsomeChenhui** [minio/minio-cpp#59]
so to use it in docker

**Comment by balamurugana** [comment]
What kind of problem are you facing?

**Comment by HandsomeChenhui** [comment]
> What kind of problem are you facing?

dependencies like unofficial-curlpp cannot be found or installed by apk or vcpkg.

**Comment by balamurugana** [comment]
`vcpkg` dependency is needed. You would need to install manually,

**Comment by HandsomeChenhui** [comment]
> to

if I use vcpkg install minio-cpp to install minio-cpp, the result would be like:
error: Failed to run "/data/chenhui/code/minio-cpp/vcpkg-master/downloads/tools/cmake-3.25.1-linux/cmake-3.25.1-linux-x86_64/bin/cmake" to determine the cmake version.
error: /data/chenhui/code/minio-cpp/vcpkg-master/downloads/tools/cmake-3.25.1-linux/cmake-3.25.1-linux-x86_64/bin/cmake failed with exit code: (127).
sh: /data/chenhui/code/minio-cpp/vcpkg-master/downloads/tools/cmake-3.25.1-linux/cmake-3.25.1-linux-x86_64/bin/cmake: not found

I think it is because the cmake vcpkg downloaded is not compitable to alpine. I use ldd to check, the result is:
/lib64/ld-linux-x86-64.so.2 (0x7f8bb739f000)
        libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f8bb739f000)
        librt.so.1 => /lib64/ld-linux-x86-64.so.2 (0x7f8bb739f000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f8bb739f000)
        libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f8bb739f000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f8bb739f000)
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /data/chenhui/code/minio-cpp/vcpkg-master/downloads/tools/cmake-3.25.1-linux/cmake-3.25.1-linux-x86_64/bin/cmake)
Error relocating /data/chenhui/code/minio-cpp/vcpkg-master/downloads/tools/cmake-3.25.1-linux/cmake-3.25.1-linux-x86_64/bin/cmake: __strdup: symbol not found
Error relocating /data/chenhui/code/minio-cpp/vcpkg-master/downloads/tools/cmake-3.25.1-linux/cmake-3.25.1-linux-x86_64/bin/cmake: __rawmemchr: symbol not found
Error relocating /data/chenhui/code/minio-cpp/vcpkg-master/downloads/tools/cmake-3.25.1-linux/cmake-3.25.1-linux-x86_64/bin/cmake: __strftime_l: symbol not found
Error relocating /data/chenhui/code/minio-cpp/vcpkg-master/downloads/tools/cmake-3.25.1-linux/cmake-3.25.1-linux-x86_64/bin/cmake: __register_atfork: symbol not found
Error relocating /data/chenhui/code/minio-cpp/vcpkg-master/downloads/tools/cmake-3.25.1-linux/cmake-3.25.1-linux-x86_64/bin/cmake: backtrace: symbol not found
Error relocating /data/chenhui/code/minio-cpp/vcpkg-master/downloads/tools/cmake-3.25.1-linux/cmake-3.25.1-linux-x86_64/bin/cmake: gnu_get_libc_version: symbol not found

It seems it is a libc problem.

**Comment by balamurugana** [comment]
I see ` sh: /data/chenhui/code/minio-cpp/vcpkg-master/downloads/tools/cmake-3.25.1-linux/cmake-3.25.1-linux-x86_64/bin/cmake: not found`. Do you have supported `cmake`?

**Comment by zyw0605688** [comment]
Alpine uses musl libc, while vcpkg's prebuilt CMake requires glibc — they are incompatible, causing executable loading failures.

**Comment by zyw0605688** [comment]
我也遇到了同样的问题，我也需要Minio-cpp，支持musl libc
