### ISSUE TITLE
[help wanted]cmake failed by vcpkg

### ISSUE THREAD

**Issue by xuyiqun-learner** [minio/minio-cpp#67]
System Info:
Edition	Windows 10 IoT Enterprise LTSC
Version	21H2
Installed on	‎3/‎17/‎2023
OS build	19044.1288
Experience	Windows Feature Experience Pack 120.2212.3920.0
![image](https://user-images.githubusercontent.com/63037112/226098130-27854da9-664b-4c6d-b08a-df942b362be1.png)
Procedure：
`git clone https://github.com/minio/minio-cpp`
`cd minio-cpp`
`wget --quiet -O vcpkg-master.zip https://github.com/microsoft/vcpkg/archive/refs/heads/master.zip`
`unzip -qq vcpkg-master.zip`
` ./vcpkg-master/bootstrap-vcpkg.sh`
`./vcpkg-master/vcpkg integrate install`
`cmake -B ./build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=./vcpkg-master/scripts/buildsystems/vcpkg.cmake`

Output Logs:
-- Running vcpkg install
-- Running vcpkg install - failed
CMake Error at vcpkg-master/scripts/buildsystems/vcpkg.cmake:892 (message):
  vcpkg install failed.  See logs for more information:
  /tmp/minio-cpp/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:16 (project)

CMake Warning (dev) in vcpkg-master/scripts/buildsystems/vcpkg.cmake:
  Policy CMP0011 is not set: Included scripts do automatic cmake_policy PUSH
  and POP.  Run "cmake --help-policy CMP0011" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  The included script
    /tmp/minio-cpp/vcpkg-master/scripts/buildsystems/vcpkg.cmake
  affects policy settings.  CMake is implying the NO_POLICY_SCOPE option for
  compatibility, so the effects are applied to the including context.
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:16 (project)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

**Comment by balamurugana** [comment]
MS Windows is not fully supported yet.

**Comment by xuyiqun-learner** [comment]
why not support CMakeLists without vcpkg to compile ?

**Comment by xuyiqun-learner** [comment]
Actually I had solved it finally a few days ago by modified your CMakeLists.

**Comment by xuyiqun-learner** [comment]
But I recur this issue on my new work PC ,So I opened this issue for possible help.

**Comment by balamurugana** [comment]
Feel free to send a PR

**Comment by xuyiqun-learner** [comment]
Solution:
` sudo apt-get install pkg-config -y`
