### ISSUE TITLE
Will there be support for Windows in the future?

### ISSUE THREAD

**Issue by Sleaon** [minio/minio-cpp#71]
We need to access Minio in the Windows app, but many parts of the source code do not support the Windows platform. Are there any plans to support Windows in the future?

**Comment by balamurugana** [comment]
Please feel free to send a PR for MS Windows support.

**Comment by harshavardhana** [comment]
> We need to access Minio in the Windows app, but many parts of the source code do not support the Windows platform. Are there any plans to support Windows in the future?

For now we do not have the necessary cycles to take this up. Feel free to send a PR to fix the build on MS Windows
