### ISSUE TITLE
How to set client with secure=false

### ISSUE THREAD

**Issue by wuxiangchao** [minio/minio-cpp#75]
I have minio server by python 

`
from minio import Minio

client = Minio("my-endpoint", "access_key", "secret_key")
`

run this code with SSLError, but add secure= False that run well, like bottom

`
from minio import Minio

client = Minio("my-endpoint", "access_key", "secret_key", secure=False)
`

 my minio-cpp client also with the error, but i don't how to add the "secure" with minio-cpp.

**Comment by balamurugana** [comment]
Use [IgnoreCertCheck()](https://github.com/minio/minio-cpp/blob/main/include/baseclient.h#L50) method.

**Comment by wuxiangchao** [comment]
> Use [IgnoreCertCheck()](https://github.com/minio/minio-cpp/blob/main/include/baseclient.h#L50) method.

I'm add minio_client.IngoreCertCheck(true) under the minio::s3::Client minio_client(url, &provider),  but do bucket exists check, the result also not exists
