### ISSUE TITLE
with openssl version error

### ISSUE THREAD

**Issue by wuxiangchao** [minio/minio-cpp#76]
with Debug has the exception:

*   Trying xxx:9722...
* Connected to xxx (xxxx) port 9722 (#0)
* ALPN: offers http/1.1
* OpenSSL/3.1.0: error:0A00010B:SSL routines::wrong version number
* Closing connection 0

i'm install minio-cpp with vcpkg install minio-cpp,

**Comment by balamurugana** [comment]
Check your server why it is failing.
