### ISSUE TITLE
Conan package.

### ISSUE THREAD

**Issue by Adrimeov** [minio/minio-cpp#81]
Hi guys ! Would it be possible to distribute the package via Conan also ?

**Comment by harshavardhana** [comment]
What is the problem with vcpkg?

**Comment by Adrimeov** [comment]
There is no problem with vcpkg per se; its just that we (and a part of the industry) decided to use Conan instead of vcpkg for various reasons; similar to Conda vs pip. I think it would be profitable for the Minio user base to have the choice.

**Comment by balamurugana** [comment]
@Adrimeov Feel free to send a PR to add a support. ATM we don't have bandwidth to support other than `vcpkg`.
