### ISSUE TITLE
OpenSSL/3.1.4: error:0A00010B:SSL routines::wrong version number

### ISSUE THREAD

**Issue by AlfengYuan** [minio/minio-cpp#99]
*   Trying ip:9000...
* Connected to ip (ip) port 9000
* ALPN: curl offers http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* OpenSSL/3.1.4: error:0A00010B:SSL routines::wrong version number
* Closing connection
unable to create bucket; 1

**Comment by AlfengYuan** [comment]
who had this problem like me, please tell me , what's wrong and how can I to deal this?

**Comment by AlfengYuan** [comment]
who had this problem like me, please tell me what's wrong, and how can I to deal it

**Comment by wsradha-rakbank** [comment]
Hi Alfend Yuan,
How you fixed this issue ?
